[package]
name = "Econia"
version = "4.2.1"
upgrade_policy = "compatible"
authors = ["Econia Labs (developers@econialabs.com)"]

[addresses]
econia = "0xABCD"
# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"
integrator = "0x4567"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
