{{- range $i, $e := until (int .Values.numFullnodeGroups) }}
{{- range $.Values.fullnode.groups }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{$i}}-{{ .name }}
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
    {{- include "aptos-validator.multiclusterLabels" (tuple $ $i) | nindent 4 }}  
spec:
  selector:
    {{- include "aptos-validator.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    app.kubernetes.io/instance: fullnode-{{$i}}
    group: {{ .name }}
  type: {{ $.Values.service.fullnode.internal.type }}
  {{- if $.Values.service.fullnode.internal.headless }}
  clusterIP: None
  {{- end }}
  ports:
  - name: aptosnet
    port: 6182
  - name: metrics
    port: 9101
  - name: api
    port: 8080

---
{{ $fullnode_statefulset := lookup "apps/v1" "StatefulSet" $.Release.Namespace (printf "%s-%d-%s-e%s" (include "aptos-validator.fullname" $) $i .name (toYaml $.Values.chain.era)) }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "aptos-validator.fullname" $ }}-{{$i}}-{{ .name }}-e{{ $.Values.chain.era }}
  labels:
    {{- include "aptos-validator.labels" $ | nindent 4 }}
    app.kubernetes.io/name: fullnode
    app.kubernetes.io/instance: fullnode-{{$i}}
    group: {{ .name }}
    {{- include "aptos-validator.multiclusterLabels" (tuple $ $i) | nindent 4 }}  
spec:
  serviceName: {{ include "aptos-validator.fullname" $ }}-{{$i}}-{{ .name }}
  replicas: {{ .replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "aptos-validator.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/name: fullnode
      app.kubernetes.io/instance: fullnode-{{$i}}
      group: {{ .name }}
  volumeClaimTemplates:
  - metadata:
      name: fn
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: {{ $.Values.fullnode.storage.class }}
      resources:
        requests:
          storage: {{ $.Values.fullnode.storage.size }}
      {{- if $.Values.fullnode.storage.labels }}
      selector:
        matchLabels:
          {{- toYaml $.Values.fullnode.storage.labels | nindent 10}}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "aptos-validator.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/name: fullnode
        app.kubernetes.io/instance: fullnode-{{$i}}
        group: {{ .name }}
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: runtime/default
        checksum/fullnode.yaml: {{ tpl ($.Files.Get "files/configs/fullnode.yaml") $ | sha256sum }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9101"
        profiles.grafana.com/memory.scrape: "true"
        profiles.grafana.com/memory.port: "8080"
        profiles.grafana.com/cpu.scrape: "true"
        profiles.grafana.com/cpu.port: "8080"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: fullnode
        {{- if and $fullnode_statefulset (not $.Values.manageImages) }} # if the statefulset already exists and we do not want helm to simply overwrite the image, use the existing image
        image: {{ (first $fullnode_statefulset.spec.template.spec.containers).image }}
        {{- else }}
        image: {{ $.Values.validator.image.repo }}:{{ $.Values.validator.image.tag | default $.Values.imageTag }}
        {{- end }}
        imagePullPolicy: {{ $.Values.validator.image.pullPolicy }}
        command: ["/usr/local/bin/aptos-node", "-f", "/opt/aptos/etc/fullnode.yaml"]
      {{- with $.Values.fullnode }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        env:
        - name: RUST_LOG
          value: {{ .rust_log }}
        {{- if .force_enable_telemetry }}
        - name: APTOS_FORCE_ENABLE_TELEMETRY
          value: "true"
        {{- end }}
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: RUST_BACKTRACE
          value: "0"
      {{- end }}
        volumeMounts:
        - name: aptos-config
          mountPath: /opt/aptos/etc
        - name: genesis-config
          mountPath: /opt/aptos/genesis
        - name: fn
          mountPath: /opt/aptos/data
        ports:
        - containerPort: 6181
        - containerPort: 6182
        - containerPort: 8080
          name: api
        - containerPort: 9101
          name: metrics
        securityContext:
          {{- if $.Values.enablePrivilegedMode }}
          runAsUser: 0
          privileged: true
          {{- else }}
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          {{- end }}
      {{- with $.Values.fullnode }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- if $.Values.enablePrivilegedMode }}
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        {{- else }}
        runAsNonRoot: true
        runAsUser: 6180
        runAsGroup: 6180
        fsGroup: 6180
        {{- end }}
      {{- end }}
      volumes:
      - name: aptos-config
        configMap:
          name: {{ include "aptos-validator.fullname" $ }}-{{$i}}
      - name: genesis-config
        secret:
          secretName: {{ include "aptos-validator.fullname" $ }}-{{$i}}-genesis-e{{ $.Values.chain.era }}
      serviceAccountName: {{ include "aptos-validator.fullname" $ }}-fullnode
      {{- if $.Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ $.Values.imagePullSecret }}
      {{- end }}

{{- end }}
{{- end }}
