name: "Aptos Move Test for Compiler V2"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'aptos-move/e2e-move-tests/**'
      - 'aptos-move/framework/**'
      - 'third_party/move/**'
  pull_request:
    paths:
      - 'aptos-move/e2e-move-tests/**'
      - 'aptos-move/framework/**'
      - 'third_party/move/**'

env:
  CARGO_INCREMENTAL: "0"
  CARGO_TERM_COLOR: always

# cancel redundant builds
concurrency:
  # cancel redundant builds on PRs (only on PR, not on branches)
  group: ${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.ref) || github.sha }}
  cancel-in-progress: true

jobs:
  # Run Aptos Move tests.
  rust-move-tests:
    runs-on: high-perf-docker
    steps:
      - uses: actions/checkout@v3
      - name: Run Aptos Move tests with compiler V2
        uses: ./.github/actions/move-tests-compiler-v2
        with:
          GIT_CREDENTIALS: ${{ secrets.GIT_CREDENTIALS }}
